#!/bin/bash

dirName=`dirname $0`
progName=`basename $0`


# Usage
# =====

function usage() {
  echo "NOM"
  echo "       $progName"
  echo "SYNOPSIS"
  echo "       $progName client_login client_password role"
  echo "DESCRIPTION"
  echo "       Requests an access token on the authentication SERVEUR using client credentials,"
  echo "       then gives all users the role roleName"
  echo "       role example : 'manager-dev:dictionary-user'"
}


# Command line
# ============

if [[ "$1" == "--help" || "$1" == "-h" || $# -ne 3 ]]; then
  usage
  exit 1
fi


# Execution
# =========

token=`${dirName}/oc-token $1 $2`

if [ "$token" == "null" ]; then
  echo "ERREUR invalid token. Please check client credentials."
  exit 1
fi

${dirName}/oc-getusers $1 $2 | cut -d ' ' -f 1 | xargs -I {} curl -i -X POST --data "{ \"role\": \"$3\" }" --header 'Content-type: application/json' --header "Authorization: Bearer $token" https://accounts.organicity.eu/permissions/users/{}/roles

