#!/bin/bash

dirName=`dirname $0`
progName=`basename $0`


# Usage
# =====

function usage() {
  echo "NOM"
  echo "       $progName"
  echo "SYNOPSIS"
  echo "       $progName client_login client_password"
  echo "DESCRIPTION"
  echo "       Requests an access token on the authentication SERVEUR using client credentials"
}


# Command line
# ============

if [[ "$1" == "--help" || "$1" == "-h" || $# -ne 2 ]]; then
  usage 
  exit 1
fi


# Execution
# =========

auth=`echo -n "${1}:$2" | base64 - | tr -d '\n'`
curl --silent -X POST --data "grant_type=client_credentials" --header "Authorization: Basic $auth" "https://accounts.organicity.eu/realms/organicity/protocol/openid-connect/token" | jq '.access_token' | cut -d '"' -f 2

